### ISSUE TITLE
"module is not defined error" when including with <script> tag

### ISSUE THREAD

**Issue by XShep** [jaredmcateer/ngVue3#13]
When going to import ngVue3 directly with a "script" tag into HTML file without using "module" type, i've been running into an issue with this:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/61496183/169066377-adaffedc-136c-4c5d-a6cd-5ffbce790a69.png)

What can i do to directly include it?

**Comment by jaredmcateer** [comment]
Hi XShep, sorry I hadn't really fully tested importing directly in the browser yet and it appears I've misconfigured the build and am exporting just commonjs and esm packages. I'll try and get a patch out today.

**Comment by jaredmcateer** [comment]
@XShep should be fixed in 0.3.3 let me know if not and I'll reopen
