### ISSUE TITLE
Issue: Tried to load AngularJS more than once

### ISSUE THREAD

**Issue by XShep** [jaredmcateer/ngVue3#22]
I have directly import the "angularjs" with script tag inside HTML. I have the legacy application based on AngularJS, and when i import ngVue3 with "import" statement - i got an warning, that i have tried to import AngularJS twice.

I think, that you have import statement inside your module, isn't it? Is it a problem to trying loading AngularJS twice? Will it call some issues?

If yes, i would like to know, how to import your module with another way?

**Comment by jaredmcateer** [comment]
I have noticed in the production app we use ngVue for that we've always have a "tried to bootstrap angular multiple times" warning. This has never been a problem but if you can make a minimal reproducible project I would definitely take a look to figure out why this is happening.

**Comment by XShep** [comment]
Sorry for long answer. If it not a problem, that it trying to load many times - no matter.
