### ISSUE TITLE
Connecting plugins to Vue (i18n)

### ISSUE THREAD

**Issue by XShep** [jaredmcateer/ngVue3#33]
Hello, i would like to connect the i18n translations to the ngVue. Tried a lot of examples, searching inside the main files. I saw that you did plugins functionality, but can you please explain how to use it, and connect for example i18n?

**Comment by jaredmcateer** [comment]
Hi, It looks like it depends whether you're using composition api or options api in your code. Make sure you're using [v9 of i18n](https://vue-i18n.intlify.dev/).

If you're using Options api you should just need to call `$ngVueProvider.use(i18n)` as described in the [Plugin/Use/Directives](https://github.com/jaredmcateer/ngVue3/blob/051a89725cf648bd5bed03929b46cd124524a9a0/packages/ngVue3/docs/plugins.md#provideusedirectives) docs

If you're using Composition API it looks like [i18n provides a composable](https://vue-i18n.intlify.dev/guide/advanced/composition.html) that you can use to use in your setup function (or script setup), so there should be no need to config ngVue at all for it.

**Comment by XShep** [comment]
Much thanks, i didn't found your documentation before. I'll close issue after successful tests.

**Comment by XShep** [comment]
Having problem with syntax, but in your example it is the same.
Saying me, that the `:` is unexpected in config of angular module
`
const ngVue = ngVue3.useNgVue();
const ngVuePlugins = ngVue3.useNgVuePlugins();

angular.module("vue.components", [ngVue, ngVuePlugins])
    .config(($ngVueProvider: NgVueProvider) => {
        $ngVueProvider.use(i18n);
    });
`

Maybe that happens because i'm importing without import statement? Btw ngVue works like that

**Comment by XShep** [comment]
Yeah, thanks a lot for help! Now it works
