### ISSUE TITLE
adding vue-i18n on my application using useNgVue

### ISSUE THREAD

**Issue by norautoSvendeville** [jaredmcateer/ngVue3#40]
Hello,
My AngularJs application is internationalised, so I'm trying to include 'vue-i18n' via NgVueProvider but without success.

Can you please help me?
Thanks

**Comment by jaredmcateer** [comment]
Can you create a small reproducible example of what you're trying to do?

Have you seen this issue? https://github.com/jaredmcateer/ngVue3/issues/33

**Comment by norautoSvendeville** [comment]
Thank you for your time,
On rereading the issue again, I've just realised that my instance wasn't correctly initialised.

So normally this code should work:
```
angular.module('newcat', [
    useNgVue(),
    useNgVuePlugins(),
]).config(($ngVueProvider: NgVueProvider) => {
    const i18n = createI18n({
        legacy: false,
        locale: 'en',
    });
    $ngVueProvider.use(i18n);
})
```
